name: Bump version

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version: ')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Determine bump type from commit message
        id: determine_bump
        run: |
          # Get the most recent commit message
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"

          bump_type="patch"
          if echo "$commit_message" | grep -iq "bump: major"; then
            bump_type="major"
          elif echo "$commit_message" | grep -iq "bump: minor"; then
            bump_type="minor"
          elif echo "$commit_message" | grep -iq "bump: patch"; then
            bump_type="patch"
          elif echo "$commit_message" | grep -iq "bump: none"; then
            bump_type="none"
          fi

          echo "Determined bump type: $bump_type"
          echo "bump_type=$bump_type" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        if: steps.determine_bump.outputs.bump_type != 'none'
        with:
          args: ${{ steps.determine_bump.outputs.bump_type }}
          # PAT needed because main is protected. Deploy keys aren't allowed for our repo, unfortunately, but that would
          # be better (https://github.com/orgs/community/discussions/25305#discussioncomment-10728028)
          github-token: ${{ secrets.VERSION_BUMP_REPO_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
