name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.detignore'
      - '**/*.detignore'
      - '*.example'
      - '**/*.example'
      - '*.json'
      - '**/*.json'
      - '*.md'
      - '**/*.md'
      - '*.png'
      - '**/*.png'
      - '*.sample'
      - '**/*.sample'
      - '*.TAG'
      - '**/*.TAG'
      - '*.yaml'
      - '**/*.yaml'
      - '*.yml'
      - '**/*.yml'
      - '!/.github/workflows/**'
      - 'docs/**'
      - '.gitignore'
      - 'changelog/**'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eval_framework_public
  HF_DATASET_CACHE_DIR: /tmp/huggingface_datasets  # <- single source of truth

jobs:
  docker-public:
    runs-on: cpu-runner-8c-32gb-01
    container: docker:dind
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: eval_framework_public
      REPO_OWNER_LC: aleph-alpha-research
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Registry Authentication
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: latest
